version: '3.5'

services:
  app:
    container_name: app
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - PORT=3000
      - VITE_API_URL=/steam/
    ports:
      - '3000:3000'